# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was generated by hand

# All the blobs necessary for edison

# system/bin
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/bin/akmd8975:/system/bin/akmd8975 \
vendor/motorola/edison/proprietary/bin/ap_gain.bin:/system/bin/ap_gain.bin \
vendor/motorola/edison/proprietary/bin/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
vendor/motorola/edison/proprietary/bin/batch:/system/bin/batch \
vendor/motorola/edison/proprietary/bin/btcmd:/system/bin/btcmd \
vendor/motorola/edison/proprietary/bin/bthelp:/system/bin/bthelp \
vendor/motorola/edison/proprietary/bin/bttest_mot:/system/bin/bttest_mot \
vendor/motorola/edison/proprietary/bin/bugtogo.sh:/system/bin/bugtogo.sh \
vendor/motorola/edison/proprietary/bin/charge_only_mode:/system/bin/charge_only_mode \
vendor/motorola/edison/proprietary/bin/chat-ril:/system/bin/chat-ril \
vendor/motorola/edison/proprietary/bin/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
vendor/motorola/edison/proprietary/bin/dumpe2fs:/system/bin/dumpe2fs \
vendor/motorola/edison/proprietary/bin/dund:/system/bin/dund \
vendor/motorola/edison/proprietary/bin/ecckeyd:/system/bin/ecckeyd \
vendor/motorola/edison/proprietary/bin/enc_mgt_tool:/system/bin/enc_mgt_tool \
vendor/motorola/edison/proprietary/bin/ftmipcd:/system/bin/ftmipcd \
vendor/motorola/edison/proprietary/bin/JuniperVPNTools:/system/bin/JuniperVPNTools \
vendor/motorola/edison/proprietary/bin/logcatd:/system/bin/logcatd \
vendor/motorola/edison/proprietary/bin/logcatd-blan:/system/bin/logcatd-blan \
vendor/motorola/edison/proprietary/bin/modemlog:/system/bin/modemlog \
vendor/motorola/edison/proprietary/bin/mot_boot_mode:/system/bin/mot_boot_mode \
vendor/motorola/edison/proprietary/bin/motobox:/system/bin/motobox \
vendor/motorola/edison/proprietary/bin/mount_cdrom.sh:/system/bin/mount_cdrom.sh \
vendor/motorola/edison/proprietary/bin/pppd-ril:/system/bin/pppd-ril \
vendor/motorola/edison/proprietary/bin/secclkd:/system/bin/secclkd \
vendor/motorola/edison/proprietary/bin/startup_smc.sh:/system/bin/startup_smc.sh \
vendor/motorola/edison/proprietary/bin/tcmd:/system/bin/tcmd \
vendor/motorola/edison/proprietary/bin/tcmdhelp:/system/bin/tcmdhelp \
vendor/motorola/edison/proprietary/bin/testpppd:/system/bin/testpppd \
vendor/motorola/edison/proprietary/bin/tty2ttyd:/system/bin/tty2ttyd \
vendor/motorola/edison/proprietary/bin/usbd:/system/bin/usbd \
vendor/motorola/edison/proprietary/bin/whisperd:/system/bin/whisperd \
vendor/motorola/edison/proprietary/bin/vpnclientpm:/system/bin/vpnclientpm \

# system/etc
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/etc/apns-conf:/system/etc/apns-conf \
vendor/motorola/edison/proprietary/etc/audio_effects.conf:/system/etc/audio_effects.conf \
vendor/motorola/edison/proprietary/etc/backup_targets.csv:/system/etc/backup_targets.csv \
vendor/motorola/edison/proprietary/etc/btpan.conf:/system/etc/btpan.conf \
vendor/motorola/edison/proprietary/etc/ecryptfs.tab:/system/etc/ecryptfs.tab \
vendor/motorola/edison/proprietary/etc/encrypt.tab:/system/etc/encrypt.tab \
vendor/motorola/edison/proprietary/etc/event-log-tags:/system/etc/event-log-tags \
vendor/motorola/edison/proprietary/etc/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
vendor/motorola/edison/proprietary/etc/opl.dat.enc:/system/etc/opl.dat.enc \
vendor/motorola/edison/proprietary/etc/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
vendor/motorola/edison/proprietary/etc/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
vendor/motorola/edison/proprietary/etc/smc_pa.ift:/system/etc/smc_pa.ift \
vendor/motorola/edison/proprietary/etc/smc_pa_pk_4_8Mb_ipa.bin:/system/etc/smc_pa_pk_4_8Mb_ipa.bin \
vendor/motorola/edison/proprietary/etc/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
vendor/motorola/edison/proprietary/etc/supportedlocales.conf:/system/etc/supportedlocales.conf \

PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/etc/firmware/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
vendor/motorola/edison/proprietary/etc/nuance/vsuite_config.xml:/system/etc/nuance/vsuite_config.xml \
vendor/motorola/edison/proprietary/etc/ppp/peers/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
vendor/motorola/edison/proprietary/etc/updatecmds/google_generic_update.txt:/system/etc/updatecmds/google_generic_update.txt \
vendor/motorola/edison/proprietary/etc/VideoEditorLite/mve.ini:/system/etc/VideoEditorLite/mve.ini \
vendor/motorola/edison/proprietary/etc/vsensor.d/MeaningFulLocation.vsensor:/system/etc/vsensor.d/MeaningFulLocation.vsensor \
vendor/motorola/edison/proprietary/etc/wifi/wlan_fem.ini:/system/etc/wifi/wlan_fem.ini \
vendor/motorola/edison/proprietary/etc/motorola/12m/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \
vendor/motorola/edison/proprietary/etc/security/suplcerts.bks:system/etc/security/suplcerts.bks \
vendor/motorola/edison/proprietary/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml:system/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml \
vendor/motorola/edison/proprietary/etc/permissions/com.verizon.hardware.telephony.lte.xml:system/etc/permissions/com.verizon.hardware.telephony.lte.xml \

# system/usr
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/usr/bin/gki_pd_notifier:system/usr/bin/gki_pd_notifier \
vendor/motorola/edison/proprietary/usr/bin/panic_daemon:system/usr/bin/panic_daemon \
vendor/motorola/edison/proprietary/usr/idc/evfwd.idc:system/usr/idc/evfwd.idc \
vendor/motorola/edison/proprietary/usr/idc/Motorola_Mobility_Motorola_HD_Dock.idc:system/usr/idc/Motorola_Mobility_Motorola_HD_Dock.idc \
vendor/motorola/edison/proprietary/usr/idc/qwerty.idc:system/usr/idc/qwerty.idc \
vendor/motorola/edison/proprietary/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \
vendor/motorola/edison/proprietary/usr/keychars/evfwd.kcm:system/usr/keychars/evfwd.kcm \
vendor/motorola/edison/proprietary/usr/keychars/omap4-keypad.kcm:system/usr/keychars/omap4-keypad.kcm \
vendor/motorola/edison/proprietary/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
vendor/motorola/edison/proprietary/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
vendor/motorola/edison/proprietary/usr/keylayout/atmxt-i2c.kl:system/usr/keylayout/atmxt-i2c.kl \
vendor/motorola/edison/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
vendor/motorola/edison/proprietary/usr/keylayout/cpcap-key.kl:system/usr/keylayout/cpcap-key.kl \
vendor/motorola/edison/proprietary/usr/keylayout/evfwd.kl:system/usr/keylayout/evfwd.kl \
vendor/motorola/edison/proprietary/usr/keylayout/omap4-keypad.kl:system/usr/keylayout/omap4-keypad.kl \
vendor/motorola/edison/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
vendor/motorola/edison/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
vendor/motorola/edison/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# system/lib
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/lib/libadkutils.so:/system/lib/libadkutils.so \
vendor/motorola/edison/proprietary/lib/libamcm.so:/system/lib/libamcm.so \
vendor/motorola/edison/proprietary/lib/libbattd.so:/system/lib/libbattd.so \
vendor/motorola/edison/proprietary/lib/libbcbmsg.so:/system/lib/libbcbmsg.so \
vendor/motorola/edison/proprietary/lib/libbt-aptx-4.0.3.so:/system/lib/libbt-aptx-4.0.3.so \
vendor/motorola/edison/proprietary/lib/libcaps.so:/system/lib/libcaps.so \
vendor/motorola/edison/proprietary/lib/libcapsjava.so:/system/lib/libcapsjava.so \
vendor/motorola/edison/proprietary/lib/libdataencrypt.so:/system/lib/libdataencrypt.so \
vendor/motorola/edison/proprietary/lib/libdataencrypt_tpa.so:/system/lib/libdataencrypt_tpa.so \
vendor/motorola/edison/proprietary/lib/libdataencrypt_utils.so:/system/lib/libdataencrypt_utils.so \
vendor/motorola/edison/proprietary/lib/libdlnahttpjni.so:/system/lib/libdlnahttpjni.so \
vendor/motorola/edison/proprietary/lib/libdlnajni.so:/system/lib/libdlnajni.so \
vendor/motorola/edison/proprietary/lib/libdlnaprofileparser.so:/system/lib/libdlnaprofileparser.so \
vendor/motorola/edison/proprietary/lib/libdlnasysjni.so:/system/lib/libdlnasysjni.so \
vendor/motorola/edison/proprietary/lib/libdmengine.so:/system/lib/libdmengine.so \
vendor/motorola/edison/proprietary/lib/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
vendor/motorola/edison/proprietary/lib/libdockcommjni.so:/system/lib/libdockcommjni.so \
vendor/motorola/edison/proprietary/lib/libevbridge.so:/system/lib/libevbridge.so \
vendor/motorola/edison/proprietary/lib/libexempi.so:/system/lib/libexempi.so \
vendor/motorola/edison/proprietary/lib/libextdispjni.so:/system/lib/libextdispjni.so \
vendor/motorola/edison/proprietary/lib/libhdcp.so:/system/lib/libhdcp.so \
vendor/motorola/edison/proprietary/lib/libhdmi.so:/system/lib/libhdmi.so \
vendor/motorola/edison/proprietary/lib/libimage_jni.so:/system/lib/libimage_jni.so \
vendor/motorola/edison/proprietary/lib/libjni_nwp.so:/system/lib/libjni_nwp.so \
vendor/motorola/edison/proprietary/lib/libmetainfo.so:/system/lib/libmetainfo.so \
vendor/motorola/edison/proprietary/lib/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
vendor/motorola/edison/proprietary/lib/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
vendor/motorola/edison/proprietary/lib/libmotdrm1.so:/system/lib/libmotdrm1.so \
vendor/motorola/edison/proprietary/lib/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
vendor/motorola/edison/proprietary/lib/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
vendor/motorola/edison/proprietary/lib/libmoto_mdmctrl.so:/system/lib/libmoto_mdmctrl.so \
vendor/motorola/edison/proprietary/lib/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
vendor/motorola/edison/proprietary/lib/libmss.so:/system/lib/libmss.so \
vendor/motorola/edison/proprietary/lib/libmss.so.sig:/system/lib/libmss.so.sig \
vendor/motorola/edison/proprietary/lib/libnativedrm1.so:/system/lib/libnativedrm1.so \
vendor/motorola/edison/proprietary/lib/libnmea.so:/system/lib/libnmea.so \
vendor/motorola/edison/proprietary/lib/libpanorama.so:/system/lib/libpanorama.so \
vendor/motorola/edison/proprietary/lib/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
vendor/motorola/edison/proprietary/lib/libPhotoEditor.so:/system/lib/libPhotoEditor.so \
vendor/motorola/edison/proprietary/lib/libphotoflow.so:/system/lib/libphotoflow.so \
vendor/motorola/edison/proprietary/lib/libpkip.so:/system/lib/libpkip.so \
vendor/motorola/edison/proprietary/lib/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
vendor/motorola/edison/proprietary/lib/libprovlib.so:/system/lib/libprovlib.so \
vendor/motorola/edison/proprietary/lib/libquicksec.so:/system/lib/libquicksec.so \
vendor/motorola/edison/proprietary/lib/librds_util.so:/system/lib/librds_util.so \
vendor/motorola/edison/proprietary/lib/libril_rds.so:/system/lib/libril_rds.so \
vendor/motorola/edison/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
vendor/motorola/edison/proprietary/lib/libsensorhub_jni.so:/system/lib/libsensorhub_jni.so \
vendor/motorola/edison/proprietary/lib/libsmapi.so:/system/lib/libsmapi.so \
vendor/motorola/edison/proprietary/lib/libtf_crypto_sst.so:/system/lib/libtf_crypto_sst.so \
vendor/motorola/edison/proprietary/lib/libtpa.so:/system/lib/libtpa.so \
vendor/motorola/edison/proprietary/lib/libtpa_core.so:/system/lib/libtpa_core.so \
vendor/motorola/edison/proprietary/lib/libui3d.so:/system/lib/libui3d.so \
vendor/motorola/edison/proprietary/lib/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
vendor/motorola/edison/proprietary/lib/libvpnclient_jni.so:/system/lib/libvpnclient_jni.so \
vendor/motorola/edison/proprietary/lib/libvsuite_mot_vs40_cmb.so:/system/lib/libvsuite_mot_vs40_cmb.so \
vendor/motorola/edison/proprietary/lib/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
vendor/motorola/edison/proprietary/lib/libWVphoneAPI.so:/system/lib/libWVphoneAPI.so \
vendor/motorola/edison/proprietary/lib/libXmp_jni.so:/system/lib/libXmp_jni.so \
vendor/motorola/edison/proprietary/lib/libxmpcore.so:/system/lib/libxmpcore.so \
vendor/motorola/edison/proprietary/lib/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
vendor/motorola/edison/proprietary/lib/libportaljni.so:/system/lib/libportaljni.so \

# RIL files
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/bin/base64:/system/bin/base64 \
vendor/motorola/edison/proprietary/bin/extract-embedded-files:/system/bin/extract-embedded-files \
vendor/motorola/edison/proprietary/bin/mm-wrigley-qc-dump.sh:/system/bin/mm-wrigley-qc-dump.sh \
vendor/motorola/edison/proprietary/bin/vril-dump:/system/bin/vril-dump \
vendor/motorola/edison/proprietary/bin/wrigley-diag.sh:/system/bin/wrigley-diag.sh \
vendor/motorola/edison/proprietary/bin/wrigley-dump.sh:/system/bin/wrigley-dump.sh \
vendor/motorola/edison/proprietary/bin/wrigley-fetch-mpr.sh:/system/bin/wrigley-fetch-mpr.sh \
vendor/motorola/edison/proprietary/lib/libbabysit.so:/system/lib/libbabysit.so \
vendor/motorola/edison/proprietary/lib/libb64.so:/system/lib/libb64.so \
vendor/motorola/edison/proprietary/lib/lib-mot-lte-ril.so:/system/lib/lib-mot-lte-ril.so \
vendor/motorola/edison/proprietary/lib/libmoto_nwif_ril.so:/system/lib/libmoto_nwif_ril.so \
vendor/motorola/edison/proprietary/lib/libmoto_qmi_ril.so:/system/lib/libmoto_qmi_ril.so \
vendor/motorola/edison/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
vendor/motorola/edison/proprietary/lib/libmotdb.so:/system/lib/libmotdb.so \
vendor/motorola/edison/proprietary/lib/moto-ril-multimode.so:/system/lib/moto-ril-multimode.so \
vendor/motorola/edison/proprietary/lib/libims_client_jni.so:/system/lib/libims_client_jni.so \

# system/lib/hw
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/lib/hw/gps.edison.so:/system/lib/hw/gps.edison.so \
vendor/motorola/edison/proprietary/lib/hw/lights.edison.so:/system/lib/hw/lights.edison.so \
vendor/motorola/edison/proprietary/lib/hw/sensors.edison.so:/system/lib/hw/sensors.edison.so \

# system/xbin
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/xbin/drm1_func_test:/system/xbin/drm1_func_test \

# Load TCMD libs
PRODUCT_COPY_FILES += \
vendor/motorola/edison/proprietary/lib/libaudiotcmd.so:/system/lib/libaudiotcmd.so \
vendor/motorola/edison/proprietary/lib/libfm_stack.so:/system/lib/libfm_stack.so \
vendor/motorola/edison/proprietary/lib/libfmchr.so:/system/lib/libfmchr.so \
vendor/motorola/edison/proprietary/lib/libmcphal.so:/system/lib/libmcphal.so \
vendor/motorola/edison/proprietary/lib/libtcmdcameraservice.so:/system/lib/libtcmdcameraservice.so \


